#! /usr/bin/env python

import sys
import os
import time
import urllib
import urllib2
import httplib
import cookielib
import getpass
import signal
import re

import yaml

from BeautifulSoup import BeautifulSoup

__version__ = "0.9.8"

class DeleteBotError(Exception):
  pass

def usage():
  print "usage: xsterminate YAMLCONFIG"
  sys.exit()


def set_exit_handler(func):
  """
  Ripped mostly from http://tinyurl.com/6vgojg6
  """
  if os.name == "nt":
    try:
      import win32api
      win32api.SetConsoleCtrlHandler(func, True)
    except ImportError:
      version = ".".join(map(str, sys.version_info[:2]))
      raise Exception("pywin32 not installed for Python " + version)
  else:
    print "Setting signal handler."
    signal.signal(signal.SIGTERM, func)
    signal.signal(signal.SIGINT, func)

def delete_link(button):
  return button.findAll("a")[-2]["href"]

def append_luser(deletes, luser, btn, thread_html):
  try:
    link = delete_link(btn)
  except Exception, e:
    crash_report(luser, thread_html, e)
  link_list = [d[1] for d in deletes]
  if link not in link_list:
    deletes.append((luser, link))

def crash_report(luser, thread_html, e):
  with open("crashreport", "wa") as f:
    f.write("============\nEXCEPTION\n\n")
    f.write(str(e) + "\n\n")
    f.write("Luser: %s\n\n" % luser)
    f.write("--- HTML ---\n")
    f.write(thread_html + "\n")
    f.write("============\n")


def run(login_success):
  if len(sys.argv) == 1:
    config_file = "deletebot.yml"
  elif len(sys.argv) == 2:
    config_file = sys.argv[1]
  else:
    usage()
  yml = open(config_file).read()
  config = yaml.load(yml)

  luser_file = config['lusers']

  # remembers when the files were last changed
  file_changed = {'lusers': 0,
                  'config': os.path.getmtime(config_file)}

  #######################################################################
  # some constants
  #######################################################################

  bct_url = "https://bitcointalk.org/index.php"

  if config.get("password", None) is None:
    config['password'] = getpass.getpass()
 
  signin_params = urllib.urlencode({"action": "login2",
                                    "user": config['user'],
                                    "passwrd": config['password'],
                                    "cookielength": "-1",
                                    "hash_passwrd": ""})

  thread_params = urllib.urlencode({"topic": str(config['topic'])})


  #######################################################################
  # setup for cookies
  #######################################################################
  cj = cookielib.LWPCookieJar()

  if os.path.isfile(config['cookiefile']):
    cj.load(config['cookiefile'])

  opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))
  urllib2.install_opener(opener)


  #######################################################################
  # make the requests
  #######################################################################
  # user_agent = 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)'
  # txheaders =  {'User-agent' : user_agent}
  # req = urllib2.Request(bct_url, signin_params, txheaders)

  signin_url = bct_url + "?" + signin_params
  thread_url = bct_url + "?" + thread_params + ".new#new"

  if config['debug']:
    print
    print "Signin URL:"
    print signin_url


  #######################################################################
  # signin and print info
  #######################################################################
  try:
    signin = urllib2.urlopen(signin_url)
  except IOError, e:
    print 'Failed to open "%s".' % signin_url
    if hasattr(e, 'code'):
      print 'Failed with error code - %s.' % e.code
  else:
    login_good = False
    for cookie in cj:
      if str(cookie).startswith("<Cookie SMFCookie"):
        login_good = True
        break
   
    if config.setdefault("debug", False):
      signin_html = signin.read()
      afile = open("signin.html", "w")
      afile.write(signin_html)
      afile.close()

    if login_good:
      # was login successful once?
      login_success = True
      print "Login successful."
    else:
      print "Bad login info."
      return login_success


  def signal_handler(signal, frame):
    print
    print "Caught exit signal."
    print "Saving cookies."
    cj.save(config['cookiefile'], True, True)
    raise SystemExit

  set_exit_handler(signal_handler)

  while True:

    lusers_changed = os.path.getmtime(luser_file)
    if lusers_changed > file_changed['lusers']: 
      if file_changed['lusers'] == 0:
        print "Loading list of lusers."
      else:
        print "Loading new list of lusers."
      file_changed['lusers'] = lusers_changed
      lusers = []
      for aline in open(config['lusers']):
        lusers.append(aline.strip())

    config_changed = os.path.getmtime(config_file)
    if config_changed > file_changed['config']:
      file_changed['config'] = config_changed
      try:
        yml = open(config_file).read()
        cfg = yaml.load(yml)
        can_change = ["sleep", "debug", "activity"]
        for setting in can_change:
          if config.get(setting) != cfg.get(setting):
            tplt = "Changing setting '%s' to `%s`."
            print tplt % (setting, cfg.get(setting))
            config[setting] = cfg.get(setting)
      except Exception, e:
        # don't crash if a good config has already loaded
        print "Problem reloading '%s'." % config_file
        print "Error was:"
        print e

    try:
      if config['debug']:
        print "Reloading at %s." % time.ctime()
      thread = urllib2.urlopen(thread_url)
      thread_html = ""
      timeout = 0
      while len(thread_html) == 0:
        if timeout > 120:
          print "Getting new messages timed out. Trying again."
          break
        time.sleep(0.1)
        timeout += 0.1
        thread_html = thread.read()
      if timeout > 120:
        continue
      if config['debug']:
        f = open("thread.html", "w")
        f.write(thread_html)
        f.close()
    except (IOError, httplib.BadStatusLine), e:
      print 'Failed to open "%s".' % thread_url
      if hasattr(e, 'code'):
        print "Failed with error code - %s." % e.code
      print "Trying again in 50 seconds."
      print "     ", time.ctime()
      time.sleep(50)
      continue

    soup = BeautifulSoup(thread_html)

    try:
      if soup.findAll('a')[1].text == "login":
        print "Session terminated, logging in again in 50 seconds."
        print "     ", time.ctime()
        time.sleep(50)
        # can't get here without a sucessful login
        return login_success
    except IndexError:
      print "Malformed response from server."
      if login_success:
        print "   Retrying in 120 seconds."
        print "       ", time.ctime()
        time.sleep(120)
      else:
        print "   Can't authenticate. Please try again in a few minutes."
        print "       ", time.ctime()
      return login_success

    user_links = soup.findAll('td', {'class': 'poster_info'})
    td_buttons = soup.findAll('td', {'class': 'td_buttons'})

    links_buttons = zip(user_links, td_buttons)

    deletes = []

    try:
      min_act = int(config['activity'])
    except (ValueError, TypeError):
      print "Setting 'activity' must be 0 or a positive integer."
      print "---> Defaulting to 0."
      min_act = 0
    except KeyError:
      if config['debug']:
        print "Setting 'activity' not specified."
        print "---> Defaulting to 0."
      min_act = 0
    if min_act > 0:
      for lnk, btn in links_buttons:
        smtxt = lnk.findAll('div', {'class': 'smalltext'})[0]
        for i in smtxt.contents:
          if "Activity" in i:
            try:
              act = int(i.split()[-1])
            except (ValueError, TypeError), e:
              crash_report(luser, thread_html, e)
            if act < min_act:
              links = lnk.findAll("a")
              luser = links[0].text
              append_luser(deletes, luser, btn, thread_html)
            break
 
    for i, luser in enumerate(lusers):
      for lnk, btn in links_buttons:
        links = lnk.findAll("a")
        if luser == links[0].text:
          append_luser(deletes, luser, btn, thread_html)
      
    if deletes:
      for i, (u, d) in enumerate(deletes):
        print d
        msg = re.search(r'msg=(\d+)', d).group(1)
        print "Deleted message `%s` of luser `%s`." % (msg, u)
        urllib2.urlopen(d)

    time.sleep(config['sleep'])

  # in principle, we never break the loop
  return login_success

def main():
  print "XSTerminate v%s" % __version__
  login_success = False
  while True:
    login_success = run(login_success)
    # break only if the first attempt failed
    if login_success == False:
      break

if __name__ == "__main__":
  main()
